### ISSUE TITLE
update-grub not working

### ISSUE THREAD

**Issue by 6r3ym0j0** [blessingmwiti/grub-background-changer#2]
After inputting the path for the background image, and running
```bash
update-grub
```
no changes were made, i even tried changing default values and run the update grub command again, but nothing changed!

**Comment by blessingmwiti** [comment]
This is because you are using grub-legacy, purge grub-legacy and install grub-efi, then re install grub

## purge grub-legacy
```bash
sudo apt purge grub-legacy
```
## install grub-efi
```bash
sudo apt install grub-efi
```
## re install grub
```bash
sudo grub-install
```
## update grub config
```bash
sudo update-grub
```
This should work

**Comment by 6r3ym0j0** [comment]
Thanks, it now updates

**Comment by blessingmwiti** [comment]
Perfect
